/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#001D36",
        "on-secondary-fixed-variant": "#1E3A8A",
        "secondary": "#4A90E2",
        "on-primary-container": "#D1E4FF",
        "on-tertiary-container": "#001D36",
        "primary-fixed": "#D1E4FF",
        "surface-container-highest": "#e2e3e0",
        "sand-silk": "#E6EDF2",
        "on-surface-variant": "#424846",
        "secondary-container": "#D1E4FF",
        "primary-container": "#1E3A8A",
        "secondary-fixed": "#D1E4FF",
        "surface-dim": "#dadad7",
        "on-secondary-container": "#001D36",
        "background": "#ffffff",
        "primary-fixed-dim": "#A0C2FF",
        "tertiary": "#1C2C58",
        "error": "#ba1a1a",
        "surface-bright": "#f9f9f6",
        "on-primary-fixed": "#001D36",
        "inverse-on-surface": "#f1f1ee",
        "surface-container": "#eeeeeb",
        "bone": "#F3F6F8",
        "error-container": "#ffdad6",
        "inverse-primary": "#A0C2FF",
        "on-tertiary-fixed-variant": "#1C2C58",
        "on-background": "#1a1c1b",
        "on-error": "#ffffff",
        "sage-haze": "#4A90E2",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary": "#1C2C58",
        "tertiary-container": "#BCE2FF",
        "surface-tint": "#4f625d",
        "on-tertiary-fixed": "#001D36",
        "surface-container-high": "#e8e8e5",
        "surface-variant": "#E6EDF2",
        "tertiary-fixed-dim": "#77C2FF",
        "outline-variant": "#c2c8c5",
        "on-surface": "#1a1c1b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#A0C2FF",
        "linen-white": "#FFFFFF",
        "on-primary-fixed-variant": "#1E3A8A",
        "inverse-surface": "#2f312f",
        "slate-deep": "#1C2C58",
        "outline": "#727876",
        "tertiary-fixed": "#BCE2FF",
        "on-primary": "#ffffff",
        "surface": "#ffffff",
        "surface-container-low": "#f4f4f1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "8px",
        "section-gap": "48px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "body-lg": ["Manrope", "sans-serif"],
        "button": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "button": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["36px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "headline-sm": ["28px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "display-md": ["42px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-md-mobile": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "300" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "300" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }]
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scan': {
          '0%': { top: '0%' },
          '50%': { top: '100%' },
          '100%': { top: '0%' },
        }
      },
      animation: {
        marquee: 'marquee 200s linear infinite',
        float: 'float 3s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.5s ease-out forwards',
        'fade-in': 'fade-in 0.3s ease-out forwards',
        'slide-in': 'slide-in 0.3s ease-out forwards',
        'scan': 'scan 2.5s ease-in-out infinite',
      }
    },
  },
  plugins: [],
}
